/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    ChatBot: typeof import('./components/ChatBot.vue')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    ImageCropper: typeof import('./components/ImageCropper.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    Report: typeof import('./components/report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
